version: "2"
run:
  go: "1.24"
linters:
  enable:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - unconvert
  settings:
    govet:
      disable:
        - structtag
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
