version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - goconst
    - gosec
    - lll
    - misspell
    - nakedret
    - unconvert
  settings:
    govet:
      disable:
        - structtag
    cyclop:
      max-complexity: 30
    dupl:
      threshold: 100
    lll:
      line-length: 200
      tab-width: 1
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/vatesfr)
        - prefix(k8s.io)
