// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatesfr/xenorchestra-go-sdk/pkg/services/library (interfaces: Library,VM,Host,Pool)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_library.go -package=mocks github.com/vatesfr/xenorchestra-go-sdk/pkg/services/library Library,VM,Host,Pool
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	client "github.com/vatesfr/xenorchestra-go-sdk/client"
	payloads "github.com/vatesfr/xenorchestra-go-sdk/pkg/payloads"
	library "github.com/vatesfr/xenorchestra-go-sdk/pkg/services/library"
	gomock "go.uber.org/mock/gomock"
)

// MockLibrary is a mock of Library interface.
type MockLibrary struct {
	ctrl     *gomock.Controller
	recorder *MockLibraryMockRecorder
	isgomock struct{}
}

// MockLibraryMockRecorder is the mock recorder for MockLibrary.
type MockLibraryMockRecorder struct {
	mock *MockLibrary
}

// NewMockLibrary creates a new mock instance.
func NewMockLibrary(ctrl *gomock.Controller) *MockLibrary {
	mock := &MockLibrary{ctrl: ctrl}
	mock.recorder = &MockLibraryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibrary) EXPECT() *MockLibraryMockRecorder {
	return m.recorder
}

// Host mocks base method.
func (m *MockLibrary) Host() library.Host {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Host")
	ret0, _ := ret[0].(library.Host)
	return ret0
}

// Host indicates an expected call of Host.
func (mr *MockLibraryMockRecorder) Host() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Host", reflect.TypeOf((*MockLibrary)(nil).Host))
}

// Pool mocks base method.
func (m *MockLibrary) Pool() library.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pool")
	ret0, _ := ret[0].(library.Pool)
	return ret0
}

// Pool indicates an expected call of Pool.
func (mr *MockLibraryMockRecorder) Pool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pool", reflect.TypeOf((*MockLibrary)(nil).Pool))
}

// Task mocks base method.
func (m *MockLibrary) Task() library.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Task")
	ret0, _ := ret[0].(library.Task)
	return ret0
}

// Task indicates an expected call of Task.
func (mr *MockLibraryMockRecorder) Task() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Task", reflect.TypeOf((*MockLibrary)(nil).Task))
}

// V1Client mocks base method.
func (m *MockLibrary) V1Client() client.XOClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "V1Client")
	ret0, _ := ret[0].(client.XOClient)
	return ret0
}

// V1Client indicates an expected call of V1Client.
func (mr *MockLibraryMockRecorder) V1Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1Client", reflect.TypeOf((*MockLibrary)(nil).V1Client))
}

// VBD mocks base method.
func (m *MockLibrary) VBD() library.VBD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VBD")
	ret0, _ := ret[0].(library.VBD)
	return ret0
}

// VBD indicates an expected call of VBD.
func (mr *MockLibraryMockRecorder) VBD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VBD", reflect.TypeOf((*MockLibrary)(nil).VBD))
}

// VDI mocks base method.
func (m *MockLibrary) VDI() library.VDI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VDI")
	ret0, _ := ret[0].(library.VDI)
	return ret0
}

// VDI indicates an expected call of VDI.
func (mr *MockLibraryMockRecorder) VDI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VDI", reflect.TypeOf((*MockLibrary)(nil).VDI))
}

// VM mocks base method.
func (m *MockLibrary) VM() library.VM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VM")
	ret0, _ := ret[0].(library.VM)
	return ret0
}

// VM indicates an expected call of VM.
func (mr *MockLibraryMockRecorder) VM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VM", reflect.TypeOf((*MockLibrary)(nil).VM))
}

// MockVM is a mock of VM interface.
type MockVM struct {
	ctrl     *gomock.Controller
	recorder *MockVMMockRecorder
	isgomock struct{}
}

// MockVMMockRecorder is the mock recorder for MockVM.
type MockVMMockRecorder struct {
	mock *MockVM
}

// NewMockVM creates a new mock instance.
func NewMockVM(ctrl *gomock.Controller) *MockVM {
	mock := &MockVM{ctrl: ctrl}
	mock.recorder = &MockVMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVM) EXPECT() *MockVMMockRecorder {
	return m.recorder
}

// CleanReboot mocks base method.
func (m *MockVM) CleanReboot(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanReboot", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanReboot indicates an expected call of CleanReboot.
func (mr *MockVMMockRecorder) CleanReboot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanReboot", reflect.TypeOf((*MockVM)(nil).CleanReboot), ctx, id)
}

// CleanShutdown mocks base method.
func (m *MockVM) CleanShutdown(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanShutdown", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanShutdown indicates an expected call of CleanShutdown.
func (mr *MockVMMockRecorder) CleanShutdown(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanShutdown", reflect.TypeOf((*MockVM)(nil).CleanShutdown), ctx, id)
}

// Create mocks base method.
func (m *MockVM) Create(ctx context.Context, poolID uuid.UUID, vm *payloads.CreateVMParams) (*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, poolID, vm)
	ret0, _ := ret[0].(*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVMMockRecorder) Create(ctx, poolID, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVM)(nil).Create), ctx, poolID, vm)
}

// Delete mocks base method.
func (m *MockVM) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVMMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVM)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockVM) GetAll(ctx context.Context, limit int, filter string) ([]*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, filter)
	ret0, _ := ret[0].([]*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockVMMockRecorder) GetAll(ctx, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockVM)(nil).GetAll), ctx, limit, filter)
}

// GetByID mocks base method.
func (m *MockVM) GetByID(ctx context.Context, id uuid.UUID) (*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVMMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVM)(nil).GetByID), ctx, id)
}

// GetVDIs mocks base method.
func (m *MockVM) GetVDIs(ctx context.Context, vmID uuid.UUID, limit int, filter string) ([]*payloads.VDI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVDIs", ctx, vmID, limit, filter)
	ret0, _ := ret[0].([]*payloads.VDI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVDIs indicates an expected call of GetVDIs.
func (mr *MockVMMockRecorder) GetVDIs(ctx, vmID, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVDIs", reflect.TypeOf((*MockVM)(nil).GetVDIs), ctx, vmID, limit, filter)
}

// HardReboot mocks base method.
func (m *MockVM) HardReboot(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardReboot", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HardReboot indicates an expected call of HardReboot.
func (mr *MockVMMockRecorder) HardReboot(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardReboot", reflect.TypeOf((*MockVM)(nil).HardReboot), ctx, id)
}

// HardShutdown mocks base method.
func (m *MockVM) HardShutdown(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardShutdown", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HardShutdown indicates an expected call of HardShutdown.
func (mr *MockVMMockRecorder) HardShutdown(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardShutdown", reflect.TypeOf((*MockVM)(nil).HardShutdown), ctx, id)
}

// List mocks base method.
func (m *MockVM) List(ctx context.Context) ([]*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVMMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVM)(nil).List), ctx)
}

// Pause mocks base method.
func (m *MockVM) Pause(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pause indicates an expected call of Pause.
func (mr *MockVMMockRecorder) Pause(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockVM)(nil).Pause), ctx, id)
}

// Restart mocks base method.
func (m *MockVM) Restart(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restart indicates an expected call of Restart.
func (mr *MockVMMockRecorder) Restart(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockVM)(nil).Restart), ctx, id)
}

// Resume mocks base method.
func (m *MockVM) Resume(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockVMMockRecorder) Resume(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockVM)(nil).Resume), ctx, id)
}

// Snapshot mocks base method.
func (m *MockVM) Snapshot(ctx context.Context, id uuid.UUID, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx, id, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockVMMockRecorder) Snapshot(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockVM)(nil).Snapshot), ctx, id, name)
}

// Start mocks base method.
func (m *MockVM) Start(ctx context.Context, id uuid.UUID, hostID *uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, id, hostID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockVMMockRecorder) Start(ctx, id, hostID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVM)(nil).Start), ctx, id, hostID)
}

// Suspend mocks base method.
func (m *MockVM) Suspend(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Suspend indicates an expected call of Suspend.
func (mr *MockVMMockRecorder) Suspend(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockVM)(nil).Suspend), ctx, id)
}

// Unpause mocks base method.
func (m *MockVM) Unpause(ctx context.Context, id uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpause", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unpause indicates an expected call of Unpause.
func (mr *MockVMMockRecorder) Unpause(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpause", reflect.TypeOf((*MockVM)(nil).Unpause), ctx, id)
}

// Update mocks base method.
func (m *MockVM) Update(ctx context.Context, vm *payloads.VM) (*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, vm)
	ret0, _ := ret[0].(*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVMMockRecorder) Update(ctx, vm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVM)(nil).Update), ctx, vm)
}

// MockHost is a mock of Host interface.
type MockHost struct {
	ctrl     *gomock.Controller
	recorder *MockHostMockRecorder
	isgomock struct{}
}

// MockHostMockRecorder is the mock recorder for MockHost.
type MockHostMockRecorder struct {
	mock *MockHost
}

// NewMockHost creates a new mock instance.
func NewMockHost(ctrl *gomock.Controller) *MockHost {
	mock := &MockHost{ctrl: ctrl}
	mock.recorder = &MockHostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHost) EXPECT() *MockHostMockRecorder {
	return m.recorder
}

// AddTag mocks base method.
func (m *MockHost) AddTag(ctx context.Context, id uuid.UUID, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", ctx, id, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTag indicates an expected call of AddTag.
func (mr *MockHostMockRecorder) AddTag(ctx, id, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockHost)(nil).AddTag), ctx, id, tag)
}

// Get mocks base method.
func (m *MockHost) Get(ctx context.Context, id uuid.UUID) (*payloads.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*payloads.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHostMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHost)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockHost) GetAll(ctx context.Context, limit int, filter string) ([]*payloads.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, filter)
	ret0, _ := ret[0].([]*payloads.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockHostMockRecorder) GetAll(ctx, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockHost)(nil).GetAll), ctx, limit, filter)
}

// RemoveTag mocks base method.
func (m *MockHost) RemoveTag(ctx context.Context, id uuid.UUID, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", ctx, id, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockHostMockRecorder) RemoveTag(ctx, id, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockHost)(nil).RemoveTag), ctx, id, tag)
}

// MockPool is a mock of Pool interface.
type MockPool struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMockRecorder
	isgomock struct{}
}

// MockPoolMockRecorder is the mock recorder for MockPool.
type MockPoolMockRecorder struct {
	mock *MockPool
}

// NewMockPool creates a new mock instance.
func NewMockPool(ctrl *gomock.Controller) *MockPool {
	mock := &MockPool{ctrl: ctrl}
	mock.recorder = &MockPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPool) EXPECT() *MockPoolMockRecorder {
	return m.recorder
}

// CreateNetwork mocks base method.
func (m *MockPool) CreateNetwork(ctx context.Context, poolID uuid.UUID, params payloads.CreateNetworkParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", ctx, poolID, params)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockPoolMockRecorder) CreateNetwork(ctx, poolID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockPool)(nil).CreateNetwork), ctx, poolID, params)
}

// CreateVM mocks base method.
func (m *MockPool) CreateVM(ctx context.Context, poolID uuid.UUID, params payloads.CreateVMParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVM", ctx, poolID, params)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVM indicates an expected call of CreateVM.
func (mr *MockPoolMockRecorder) CreateVM(ctx, poolID, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVM", reflect.TypeOf((*MockPool)(nil).CreateVM), ctx, poolID, params)
}

// EmergencyShutdown mocks base method.
func (m *MockPool) EmergencyShutdown(ctx context.Context, poolID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmergencyShutdown", ctx, poolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmergencyShutdown indicates an expected call of EmergencyShutdown.
func (mr *MockPoolMockRecorder) EmergencyShutdown(ctx, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmergencyShutdown", reflect.TypeOf((*MockPool)(nil).EmergencyShutdown), ctx, poolID)
}

// Get mocks base method.
func (m *MockPool) Get(ctx context.Context, id uuid.UUID) (*payloads.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*payloads.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPoolMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPool)(nil).Get), ctx, id)
}

// GetAll mocks base method.
func (m *MockPool) GetAll(ctx context.Context, limit int, filter string) ([]*payloads.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, limit, filter)
	ret0, _ := ret[0].([]*payloads.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPoolMockRecorder) GetAll(ctx, limit, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPool)(nil).GetAll), ctx, limit, filter)
}

// RollingReboot mocks base method.
func (m *MockPool) RollingReboot(ctx context.Context, poolID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollingReboot", ctx, poolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollingReboot indicates an expected call of RollingReboot.
func (mr *MockPoolMockRecorder) RollingReboot(ctx, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollingReboot", reflect.TypeOf((*MockPool)(nil).RollingReboot), ctx, poolID)
}

// RollingUpdate mocks base method.
func (m *MockPool) RollingUpdate(ctx context.Context, poolID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollingUpdate", ctx, poolID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollingUpdate indicates an expected call of RollingUpdate.
func (mr *MockPoolMockRecorder) RollingUpdate(ctx, poolID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollingUpdate", reflect.TypeOf((*MockPool)(nil).RollingUpdate), ctx, poolID)
}
