// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vatesfr/xenorchestra-go-sdk/pkg/services/library (interfaces: Library,VM,Host,Pool)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/gofrs/uuid"
	gomock "github.com/golang/mock/gomock"
	client "github.com/vatesfr/xenorchestra-go-sdk/client"
	payloads "github.com/vatesfr/xenorchestra-go-sdk/pkg/payloads"
	library "github.com/vatesfr/xenorchestra-go-sdk/pkg/services/library"
)

// MockLibrary is a mock of Library interface.
type MockLibrary struct {
	ctrl     *gomock.Controller
	recorder *MockLibraryMockRecorder
}

// MockLibraryMockRecorder is the mock recorder for MockLibrary.
type MockLibraryMockRecorder struct {
	mock *MockLibrary
}

// NewMockLibrary creates a new mock instance.
func NewMockLibrary(ctrl *gomock.Controller) *MockLibrary {
	mock := &MockLibrary{ctrl: ctrl}
	mock.recorder = &MockLibraryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLibrary) EXPECT() *MockLibraryMockRecorder {
	return m.recorder
}

// Host mocks base method.
func (m *MockLibrary) Host() library.Host {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Host")
	ret0, _ := ret[0].(library.Host)
	return ret0
}

// Host indicates an expected call of Host.
func (mr *MockLibraryMockRecorder) Host() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Host", reflect.TypeOf((*MockLibrary)(nil).Host))
}

// Pool mocks base method.
func (m *MockLibrary) Pool() library.Pool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pool")
	ret0, _ := ret[0].(library.Pool)
	return ret0
}

// Pool indicates an expected call of Pool.
func (mr *MockLibraryMockRecorder) Pool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pool", reflect.TypeOf((*MockLibrary)(nil).Pool))
}

// Task mocks base method.
func (m *MockLibrary) Task() library.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Task")
	ret0, _ := ret[0].(library.Task)
	return ret0
}

// Task indicates an expected call of Task.
func (mr *MockLibraryMockRecorder) Task() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Task", reflect.TypeOf((*MockLibrary)(nil).Task))
}

// V1Client mocks base method.
func (m *MockLibrary) V1Client() client.XOClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "V1Client")
	ret0, _ := ret[0].(client.XOClient)
	return ret0
}

// V1Client indicates an expected call of V1Client.
func (mr *MockLibraryMockRecorder) V1Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "V1Client", reflect.TypeOf((*MockLibrary)(nil).V1Client))
}

// VBD mocks base method.
func (m *MockLibrary) VBD() library.VBD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VBD")
	ret0, _ := ret[0].(library.VBD)
	return ret0
}

// VBD indicates an expected call of VBD.
func (mr *MockLibraryMockRecorder) VBD() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VBD", reflect.TypeOf((*MockLibrary)(nil).VBD))
}

// VDI mocks base method.
func (m *MockLibrary) VDI() library.VDI {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VDI")
	ret0, _ := ret[0].(library.VDI)
	return ret0
}

// VDI indicates an expected call of VDI.
func (mr *MockLibraryMockRecorder) VDI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VDI", reflect.TypeOf((*MockLibrary)(nil).VDI))
}

// VM mocks base method.
func (m *MockLibrary) VM() library.VM {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VM")
	ret0, _ := ret[0].(library.VM)
	return ret0
}

// VM indicates an expected call of VM.
func (mr *MockLibraryMockRecorder) VM() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VM", reflect.TypeOf((*MockLibrary)(nil).VM))
}

// MockVM is a mock of VM interface.
type MockVM struct {
	ctrl     *gomock.Controller
	recorder *MockVMMockRecorder
}

// MockVMMockRecorder is the mock recorder for MockVM.
type MockVMMockRecorder struct {
	mock *MockVM
}

// NewMockVM creates a new mock instance.
func NewMockVM(ctrl *gomock.Controller) *MockVM {
	mock := &MockVM{ctrl: ctrl}
	mock.recorder = &MockVMMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVM) EXPECT() *MockVMMockRecorder {
	return m.recorder
}

// CleanReboot mocks base method.
func (m *MockVM) CleanReboot(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanReboot", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanReboot indicates an expected call of CleanReboot.
func (mr *MockVMMockRecorder) CleanReboot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanReboot", reflect.TypeOf((*MockVM)(nil).CleanReboot), arg0, arg1)
}

// CleanShutdown mocks base method.
func (m *MockVM) CleanShutdown(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanShutdown", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanShutdown indicates an expected call of CleanShutdown.
func (mr *MockVMMockRecorder) CleanShutdown(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanShutdown", reflect.TypeOf((*MockVM)(nil).CleanShutdown), arg0, arg1)
}

// Create mocks base method.
func (m *MockVM) Create(arg0 context.Context, arg1 uuid.UUID, arg2 *payloads.CreateVMParams) (*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVMMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVM)(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockVM) Delete(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVMMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVM)(nil).Delete), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockVM) GetAll(arg0 context.Context, arg1 int, arg2 string) ([]*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockVMMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockVM)(nil).GetAll), arg0, arg1, arg2)
}

// GetByID mocks base method.
func (m *MockVM) GetByID(arg0 context.Context, arg1 uuid.UUID) (*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockVMMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockVM)(nil).GetByID), arg0, arg1)
}

// GetVDIs mocks base method.
func (m *MockVM) GetVDIs(arg0 context.Context, arg1 uuid.UUID, arg2 int, arg3 string) ([]*payloads.VDI, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVDIs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*payloads.VDI)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVDIs indicates an expected call of GetVDIs.
func (mr *MockVMMockRecorder) GetVDIs(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVDIs", reflect.TypeOf((*MockVM)(nil).GetVDIs), arg0, arg1, arg2, arg3)
}

// HardReboot mocks base method.
func (m *MockVM) HardReboot(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardReboot", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HardReboot indicates an expected call of HardReboot.
func (mr *MockVMMockRecorder) HardReboot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardReboot", reflect.TypeOf((*MockVM)(nil).HardReboot), arg0, arg1)
}

// HardShutdown mocks base method.
func (m *MockVM) HardShutdown(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardShutdown", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HardShutdown indicates an expected call of HardShutdown.
func (mr *MockVMMockRecorder) HardShutdown(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardShutdown", reflect.TypeOf((*MockVM)(nil).HardShutdown), arg0, arg1)
}

// List mocks base method.
func (m *MockVM) List(arg0 context.Context) ([]*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVMMockRecorder) List(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVM)(nil).List), arg0)
}

// Pause mocks base method.
func (m *MockVM) Pause(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pause indicates an expected call of Pause.
func (mr *MockVMMockRecorder) Pause(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockVM)(nil).Pause), arg0, arg1)
}

// Restart mocks base method.
func (m *MockVM) Restart(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restart", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restart indicates an expected call of Restart.
func (mr *MockVMMockRecorder) Restart(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restart", reflect.TypeOf((*MockVM)(nil).Restart), arg0, arg1)
}

// Resume mocks base method.
func (m *MockVM) Resume(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resume indicates an expected call of Resume.
func (mr *MockVMMockRecorder) Resume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockVM)(nil).Resume), arg0, arg1)
}

// Snapshot mocks base method.
func (m *MockVM) Snapshot(arg0 context.Context, arg1 uuid.UUID, arg2 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockVMMockRecorder) Snapshot(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockVM)(nil).Snapshot), arg0, arg1, arg2)
}

// Start mocks base method.
func (m *MockVM) Start(arg0 context.Context, arg1 uuid.UUID, arg2 *uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockVMMockRecorder) Start(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVM)(nil).Start), arg0, arg1, arg2)
}

// Suspend mocks base method.
func (m *MockVM) Suspend(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Suspend", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Suspend indicates an expected call of Suspend.
func (mr *MockVMMockRecorder) Suspend(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Suspend", reflect.TypeOf((*MockVM)(nil).Suspend), arg0, arg1)
}

// Unpause mocks base method.
func (m *MockVM) Unpause(arg0 context.Context, arg1 uuid.UUID) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpause", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unpause indicates an expected call of Unpause.
func (mr *MockVMMockRecorder) Unpause(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpause", reflect.TypeOf((*MockVM)(nil).Unpause), arg0, arg1)
}

// Update mocks base method.
func (m *MockVM) Update(arg0 context.Context, arg1 *payloads.VM) (*payloads.VM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*payloads.VM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVMMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVM)(nil).Update), arg0, arg1)
}

// MockHost is a mock of Host interface.
type MockHost struct {
	ctrl     *gomock.Controller
	recorder *MockHostMockRecorder
}

// MockHostMockRecorder is the mock recorder for MockHost.
type MockHostMockRecorder struct {
	mock *MockHost
}

// NewMockHost creates a new mock instance.
func NewMockHost(ctrl *gomock.Controller) *MockHost {
	mock := &MockHost{ctrl: ctrl}
	mock.recorder = &MockHostMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHost) EXPECT() *MockHostMockRecorder {
	return m.recorder
}

// AddTag mocks base method.
func (m *MockHost) AddTag(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTag", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTag indicates an expected call of AddTag.
func (mr *MockHostMockRecorder) AddTag(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTag", reflect.TypeOf((*MockHost)(nil).AddTag), arg0, arg1, arg2)
}

// Get mocks base method.
func (m *MockHost) Get(arg0 context.Context, arg1 uuid.UUID) (*payloads.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*payloads.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHostMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHost)(nil).Get), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockHost) GetAll(arg0 context.Context, arg1 int, arg2 string) ([]*payloads.Host, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*payloads.Host)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockHostMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockHost)(nil).GetAll), arg0, arg1, arg2)
}

// RemoveTag mocks base method.
func (m *MockHost) RemoveTag(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockHostMockRecorder) RemoveTag(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockHost)(nil).RemoveTag), arg0, arg1, arg2)
}

// MockPool is a mock of Pool interface.
type MockPool struct {
	ctrl     *gomock.Controller
	recorder *MockPoolMockRecorder
}

// MockPoolMockRecorder is the mock recorder for MockPool.
type MockPoolMockRecorder struct {
	mock *MockPool
}

// NewMockPool creates a new mock instance.
func NewMockPool(ctrl *gomock.Controller) *MockPool {
	mock := &MockPool{ctrl: ctrl}
	mock.recorder = &MockPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPool) EXPECT() *MockPoolMockRecorder {
	return m.recorder
}

// CreateNetwork mocks base method.
func (m *MockPool) CreateNetwork(arg0 context.Context, arg1 uuid.UUID, arg2 payloads.CreateNetworkParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNetwork", arg0, arg1, arg2)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNetwork indicates an expected call of CreateNetwork.
func (mr *MockPoolMockRecorder) CreateNetwork(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNetwork", reflect.TypeOf((*MockPool)(nil).CreateNetwork), arg0, arg1, arg2)
}

// CreateVM mocks base method.
func (m *MockPool) CreateVM(arg0 context.Context, arg1 uuid.UUID, arg2 payloads.CreateVMParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVM", arg0, arg1, arg2)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVM indicates an expected call of CreateVM.
func (mr *MockPoolMockRecorder) CreateVM(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVM", reflect.TypeOf((*MockPool)(nil).CreateVM), arg0, arg1, arg2)
}

// EmergencyShutdown mocks base method.
func (m *MockPool) EmergencyShutdown(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmergencyShutdown", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// EmergencyShutdown indicates an expected call of EmergencyShutdown.
func (mr *MockPoolMockRecorder) EmergencyShutdown(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmergencyShutdown", reflect.TypeOf((*MockPool)(nil).EmergencyShutdown), arg0, arg1)
}

// Get mocks base method.
func (m *MockPool) Get(arg0 context.Context, arg1 uuid.UUID) (*payloads.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*payloads.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPoolMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPool)(nil).Get), arg0, arg1)
}

// GetAll mocks base method.
func (m *MockPool) GetAll(arg0 context.Context, arg1 int, arg2 string) ([]*payloads.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*payloads.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPoolMockRecorder) GetAll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPool)(nil).GetAll), arg0, arg1, arg2)
}

// RollingReboot mocks base method.
func (m *MockPool) RollingReboot(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollingReboot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollingReboot indicates an expected call of RollingReboot.
func (mr *MockPoolMockRecorder) RollingReboot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollingReboot", reflect.TypeOf((*MockPool)(nil).RollingReboot), arg0, arg1)
}

// RollingUpdate mocks base method.
func (m *MockPool) RollingUpdate(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollingUpdate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollingUpdate indicates an expected call of RollingUpdate.
func (mr *MockPoolMockRecorder) RollingUpdate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollingUpdate", reflect.TypeOf((*MockPool)(nil).RollingUpdate), arg0, arg1)
}
